Name: tensorflow

Version: 2.0.0a0

Summary: TensorFlow is an open source machine learning framework for everyone.

Home-page: https://www.tensorflow.org/

Author: Google Inc.

Author-email: packages@tensorflow.org

License: Apache 2.0

Location: /usr/lib64/python3.6/site-packages

Requires: tb-nightly, six, tf-estimator-nightly, astor, termcolor, keras-preprocessing, keras-applications, 
grpcio, numpy, protobuf, wheel, absl-py, google-pasta, gast

Required-by:

In [2]:
import tensorflow as tf

import tensorflow.keras as keras

import numpy

import pandas

from datetime import datetime

from sklearn.model_selection import train_test_split

import scipy.stats

/usr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [3]:
%load_ext tensorboard.notebook

> Ou seja, só o "country" fica vazio de vez em quando (já tirei fora essa coluna)

In [4]:
users = pandas.read_csv('train/user_data.csv', usecols=lambda x: x not in ['country', 'last_online_time_seconds', 'registration_time_seconds'])
users = pandas.concat([users, pandas.DataFrame({'user_id_num': list(range(len(users)))})], axis=1)

In [5]:
users

,user_id,submission_count,problem_solved,contribution,follower_count,max_rating,rating,rank,user_id_num
0,user_3311,47,40,0,4,348.337,330.849,intermediate,0
1,user_3028,63,52,0,17,405.677,339.450,intermediate,1
2,user_2268,226,203,-8,24,307.339,284.404,beginner,2
3,user_480,611,490,1,94,525.803,471.330,advanced,3
4,user_650,504,479,12,4,548.739,486.525,advanced,4
5,user_3177,3,1,0,0,331.135,331.135,intermediate,5
6,user_2032,216,199,0,28,387.328,387.328,intermediate,6
7,user_3306,2,1,0,0,304.186,281.250,beginner,7
8,user_1483,91,79,0,0,318.807,258.888,beginner,8
9,user_667,91,71,0,4,383.028,362.959,intermediate,9
10,user_2871,12,12,0,16,484.805,484.805,advanced,10
11,user_972,473,441,0,88,491.112,403.670,intermediate,11
12,user_1972,107,99,0,11,304.186,203.842,beginner,12
13,user_3031,669,632,0,63,356.938,303.899,beginner,13
14,user_2771,229,218,0,6,375.000,355.218,intermediate,14
15,user_991,338,311,0,14,361.525,341.743,intermediate,15
16,user_663,482,463,-3,114,452.408,418.291,intermediate,16
17,user_347,367,300,15,117,619.839,564.507,advanced,17
18,user_1258,422,384,-1,25,352.638,263.475,beginner,18
19,user_1122,145,118,0,3,313.073,261.468,beginner,19
20,user_2596,229,222,-4,3,441.514,407.683,intermediate,20
21,user_2377,7,6,0,0,360.092,327.122,intermediate,21
22,user_2620,80,65,0,3,317.087,292.431,beginner,22
23,user_2450,55,49,0,8,428.899,382.741,intermediate,23
24,user_1930,772,686,13,50,618.693,569.667,advanced,24
25,user_3317,735,715,0,9,419.438,353.211,intermediate,25
26,user_1562,455,408,0,39,397.936,389.335,intermediate,26
27,user_1469,40,33,0,1,371.560,303.326,beginner,27
28,user_564,250,223,-1,25,411.124,401.950,intermediate,28
29,user_1863,488,440,3,89,423.165,409.117,intermediate,29
...,...,...,...,...,...,...,...,...,...
3541,user_155,295,247,-15,31,366.686,335.722,intermediate,3541
3542,user_1021,6,5,0,0,317.947,261.755,beginner,3542
3543,user_1255,579,538,0,94,485.092,466.456,advanced,3543
3544,user_752,74,64,0,7,307.339,112.672,beginner,3544
3545,user_2910,48,38,0,5,316.514,316.514,intermediate,3545
3546,user_2964,232,228,0,10,321.674,311.353,beginner,3546
3547,user_1019,199,177,0,10,342.030,342.030,intermediate,3547
3548,user_3551,573,532,35,407,748.280,748.280,expert,3548
3549,user_1069,750,558,0,1,309.633,305.046,beginner,3549
3550,user_2839,126,95,0,21,337.729,337.729,intermediate,3550
3551,user_205,23,12,0,0,315.080,271.502,beginner,3551
3552,user_2443,664,622,50,196,533.257,507.454,advanced,3552
3553,user_3330,326,311,3,2,315.367,294.438,beginner,3553
3554,user_1066,286,264,11,50,464.736,422.305,intermediate,3554
3555,user_3399,13,7,0,0,304.186,292.718,beginner,3555
3556,user_2890,244,157,0,21,305.619,197.534,beginner,3556
3557,user_1638,365,296,3,56,397.649,328.555,intermediate,3557
3558,user_717,58,55,0,1,346.044,313.933,intermediate,3558
3559,user_492,35,28,0,8,311.353,290.138,beginner,3559
3560,user_1209,840,782,157,959,735.665,663.704,expert,3560
3561,user_2621,129,105,0,5,312.500,275.516,beginner,3561
3562,user_3296,665,660,0,39,549.885,549.885,advanced,3562
3563,user_2762,453,388,14,69,690.367,646.216,expert,3563
3564,user_1872,224,210,-20,8,317.661,291.858,beginner,3564
3565,user_896,459,398,0,56,313.933,235.952,beginner,3565
3566,user_2685,161,120,0,42,306.193,246.560,beginner,3566
3567,user_1548,41,30,0,0,331.135,218.463,beginner,3567
3568,user_1929,58,51,0,0,330.275,262.901,beginner,3568
3569,user_2772,148,137,0,2,409.977,345.757,intermediate,3569
3570,user_2179,163,115,6,40,392.775,288.704,beginner,3570

In [6]:
problems = pandas.read_csv('train/problem_data.csv')
problems = pandas.concat([problems, pandas.DataFrame({'problem_id_num': list(range(len(problems)))})], axis=1)
problems

,problem_id,level_type,points,tags,problem_id_num
0,prob_3649,H,NaN,NaN,0
1,prob_6191,A,NaN,NaN,1
2,prob_2020,F,NaN,NaN,2
3,prob_313,A,500.0,"greedy,implementation",3
4,prob_101,A,500.0,"constructive algorithms,greedy,math",4
5,prob_1479,E,NaN,NaN,5
6,prob_2940,B,NaN,NaN,6
7,prob_3059,B,5.0,brute force,7
8,prob_1958,D,NaN,NaN,8
9,prob_6154,C,NaN,NaN,9
10,prob_4069,B,1000.0,"dfs and similar,dsu,graphs",10
11,prob_4926,A,500.0,implementation,11
12,prob_3154,K,NaN,NaN,12
13,prob_1538,A,NaN,NaN,13
14,prob_3750,B,1000.0,math,14
15,prob_4440,I,NaN,NaN,15
16,prob_4569,A,NaN,NaN,16
17,prob_4189,D,NaN,NaN,17
18,prob_526,D,2000.0,"math,number theory",18
19,prob_5498,I,NaN,NaN,19
20,prob_3216,F,NaN,NaN,20
21,prob_1412,C,1500.0,"brute force,dp,number theory",21
22,prob_5088,B,NaN,NaN,22
23,prob_5693,D,2000.0,"brute force,dfs and similar,graphs",23
24,prob_75,A,500.0,implementation,24
25,prob_1035,I,NaN,NaN,25
26,prob_2822,C,NaN,"data structures,expression parsing,math",26
27,prob_3277,D,2000.0,"dfs and similar,greedy",27
28,prob_3284,NaN,NaN,NaN,28
29,prob_3714,D,NaN,NaN,29
...,...,...,...,...,...
6514,prob_3582,I,NaN,NaN,6514
6515,prob_3195,D,NaN,NaN,6515
6516,prob_2594,A,500.0,"math,number theory",6516
6517,prob_5657,J,NaN,NaN,6517
6518,prob_6128,G,NaN,NaN,6518
6519,prob_4870,C,1500.0,"greedy,implementation",6519
6520,prob_109,E,NaN,NaN,6520
6521,prob_4512,D,NaN,"data structures,implementation,sortings",6521
6522,prob_2152,A,500.0,"math,number theory",6522
6523,prob_6202,I,NaN,NaN,6523
6524,prob_6192,C,NaN,NaN,6524
6525,prob_4405,A,500.0,greedy,6525
6526,prob_6232,N,NaN,NaN,6526
6527,prob_5620,D,NaN,NaN,6527
6528,prob_2317,G,NaN,NaN,6528
6529,prob_1047,C,NaN,brute force,6529
6530,prob_5072,B,NaN,NaN,6530
6531,prob_441,E,NaN,NaN,6531
6532,prob_631,B,1000.0,"constructive algorithms,implementation",6532
6533,prob_2896,J,NaN,NaN,6533
6534,prob_2390,J,NaN,NaN,6534
6535,prob_3160,B,1000.0,"binary search,geometry",6535
6536,prob_933,D,NaN,NaN,6536
6537,prob_1311,B,1000.0,"constructive algorithms,geometry,greedy,sortings",6537
6538,prob_2482,E,NaN,NaN,6538
6539,prob_3989,K,NaN,NaN,6539
6540,prob_2710,A,500.0,"dfs and similar,dsu",6540
6541,prob_3269,C,1500.0,"brute force,number theory",6541
6542,prob_5071,A,500.0,implementation,6542
6543,prob_1124,B,NaN,NaN,6543

> labels garantidamente todos preenchidos (já verifiquei. Comentado abaixo)

In [7]:
labels = pandas.read_csv('train/train_submissions.csv')
# any(map(lambda value: any(list(map(lambda x: isinstance(x, float) and numpy.isnan(x), value))), labels.values))
labels

          user_id problem_id  attempts_range
0        user_232  prob_6507               1
1       user_3568  prob_2994               3
2       user_1600  prob_5071               1
3       user_2256   prob_703               1
4       user_2321   prob_356               1
5       user_1569  prob_6064               1
6       user_3293  prob_1237               1
7        user_915  prob_4125               2
8       user_2032  prob_1943               1
9       user_1410  prob_3935               1
10      user_2085  prob_5436               1
11      user_1810  prob_3431               2
12      user_1287  prob_3474               1
13      user_2063  prob_2872               1
14       user_724  prob_6043               2
15        user_88  prob_1914               2
16      user_2269  prob_5641               1
17       user_489   prob_522               1
18      user_1997    prob_32               1
19      user_1929  prob_5731               2
20      user_2084  prob_4232               1
21       user_923  prob_3508               2
22       user_150  prob_6488               1
23      user_2898  prob_1605               1
24      user_3086  prob_2605               1
25      user_2552   prob_534               1
26       user_508  prob_3073               1
27      user_1910  prob_6442               4
28      user_1066   prob_106               1
29      user_1637  prob_1482               1
...           ...        ...             ...
155265  user_1813  prob_1677               1
155266   user_948  prob_4835               1
155267  user_1093  prob_4087               1
155268   user_144  prob_4702               2
155269  user_2407  prob_1396               2
155270  user_2321  prob_4152               2
155271  user_2507  prob_1737               4
155272   user_727   prob_137               1
155273  user_2635  prob_5045               1
155274  user_3114  prob_3445               2
155275  user_2928  prob_5333               1
155276  user_1433  prob_2936               3
155277   user_595    prob_95               1
155278  user_3151  prob_5374               1
155279  user_1346  prob_5995               1
155280  user_1588  prob_5781               1
155281  user_1529  prob_1679               1
155282  user_2815  prob_5880               1
155283  user_3461  prob_5150               1
155284  user_3013  prob_2284               1
155285  user_1563   prob_740               1
155286  user_2838  prob_1181               1
155287  user_1533  prob_5837               2
155288  user_3205  prob_3474               1
155289  user_3271  prob_5932               2
155290  user_2959  prob_2052               1
155291  user_2530  prob_6167               6
155292   user_445  prob_3110               1
155293  user_2337  prob_2685               2
155294  user_1645  prob_4511               2

[155295 rows x 3 columns]

In [8]:
aggregate = pandas.merge(pandas.merge(labels,users,on='user_id',how='inner'), problems, on='problem_id', how='inner')
aggregate

,user_id,problem_id,attempts_range,submission_count,problem_solved,contribution,follower_count,max_rating,rating,rank,user_id_num,level_type,points,tags,problem_id_num
0,user_232,prob_6507,1,53,47,0,1,307.913,206.709,beginner,1308,B,1000.0,strings,4786
1,user_1910,prob_6507,2,240,218,0,50,319.954,291.284,beginner,846,B,1000.0,strings,4786
2,user_1824,prob_6507,2,370,336,-10,30,307.339,295.585,beginner,941,B,1000.0,strings,4786
3,user_895,prob_6507,1,318,286,0,20,304.186,191.514,beginner,359,B,1000.0,strings,4786
4,user_779,prob_6507,1,463,410,0,39,374.713,374.713,intermediate,60,B,1000.0,strings,4786
5,user_2246,prob_6507,2,181,142,0,23,313.073,282.397,beginner,2436,B,1000.0,strings,4786
6,user_2292,prob_6507,2,57,38,0,1,315.367,270.929,beginner,1533,B,1000.0,strings,4786
7,user_309,prob_6507,3,808,708,-27,33,406.537,343.463,intermediate,3064,B,1000.0,strings,4786
8,user_3416,prob_6507,2,192,184,0,1,337.443,280.963,beginner,414,B,1000.0,strings,4786
9,user_684,prob_6507,3,148,122,0,6,314.220,300.459,beginner,185,B,1000.0,strings,4786
10,user_1618,prob_6507,3,944,879,103,737,588.589,545.872,advanced,89,B,1000.0,strings,4786
11,user_316,prob_6507,1,153,137,0,33,306.193,272.649,beginner,1021,B,1000.0,strings,4786
12,user_2490,prob_6507,3,77,69,0,10,305.046,299.599,beginner,1643,B,1000.0,strings,4786
13,user_1065,prob_6507,2,300,247,0,31,333.142,333.142,intermediate,3281,B,1000.0,strings,4786
14,user_1686,prob_6507,2,123,88,0,11,307.339,242.833,beginner,1900,B,1000.0,strings,4786
15,user_232,prob_5781,1,53,47,0,1,307.913,206.709,beginner,1308,A,500.0,"implementation,math",4353
16,user_3568,prob_5781,1,133,118,0,0,324.255,235.378,beginner,2803,A,500.0,"implementation,math",4353
17,user_1600,prob_5781,1,50,44,0,7,343.177,229.358,beginner,568,A,500.0,"implementation,math",4353
18,user_2256,prob_5781,1,271,233,23,40,436.927,399.083,intermediate,3485,A,500.0,"implementation,math",4353
19,user_1410,prob_5781,1,390,350,0,56,315.367,217.890,beginner,249,A,500.0,"implementation,math",4353
20,user_1287,prob_5781,1,294,268,0,35,475.631,475.631,advanced,1359,A,500.0,"implementation,math",4353
21,user_489,prob_5781,1,112,97,0,5,320.528,295.298,beginner,481,A,500.0,"implementation,math",4353
22,user_1910,prob_5781,1,240,218,0,50,319.954,291.284,beginner,846,A,500.0,"implementation,math",4353
23,user_812,prob_5781,1,323,294,0,29,327.122,305.333,beginner,1136,A,500.0,"implementation,math",4353
24,user_1102,prob_5781,1,135,119,0,13,383.601,371.560,intermediate,942,A,500.0,"implementation,math",4353
25,user_771,prob_5781,1,329,319,0,8,338.303,300.459,beginner,867,A,500.0,"implementation,math",4353
26,user_3155,prob_5781,2,93,75,0,0,305.619,180.906,beginner,3168,A,500.0,"implementation,math",4353
27,user_1964,prob_5781,1,329,270,-9,29,356.651,340.596,intermediate,2050,A,500.0,"implementation,math",4353
28,user_2833,prob_5781,1,57,48,0,7,399.369,387.615,intermediate,1154,A,500.0,"implementation,math",4353
29,user_2431,prob_5781,1,178,154,3,21,486.525,454.702,intermediate,434,A,500.0,"implementation,math",4353
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155265,user_2476,prob_1147,2,1229,1208,3,149,549.885,494.839,advanced,2069,C,NaN,"greedy,hashing,string suffix structures",1757
155266,user_1105,prob_4871,2,671,605,11,217,572.821,568.807,advanced,2042,D,NaN,NaN,57
155267,user_1131,prob_4042,2,87,84,0,8,497.133,497.133,advanced,637,E,2000.0,NaN,1180
155268,user_1604,prob_3158,6,322,282,11,35,529.243,529.243,advanced,272,B,NaN,NaN,1106
155269,user_1604,prob_3376,2,322,282,11,35,529.243,529.243,advanced,272,H,NaN,NaN,2516
155270,user_1604,prob_5465,4,322,282,11,35,529.243,529.243,advanced,272,I,NaN,NaN,4671
155271,user_1604,prob_3726,4,322,282,11,35,529.243,529.243,advanced,272,C,NaN,NaN,6028
155272,user_1604,prob_5943,2,322,282,11,35,529.243,529.243,advanced,272,G,NaN,NaN,6185
155273,user_1604,prob_2586,1,322,282,11,35,529.243,529.243,advanced,272,I,NaN,NaN,2806
155274,user_1604,prob_6078,6,322,282,11,35,529.243,529.243,advanced,272,J,NaN,NaN,236
155275,user_1604,prob_4520,3,322,282,11,35,529.243,529.243,advanced,272,H,NaN,NaN,1457
155276,user_1868,prob_218,2,254,204,0,29,429.186,368.406,intermediate,2428,D,NaN,NaN,6294
155277,user_1868,prob_125,5,254,204,0,29,429.186,368.406,intermediate,2428,J,NaN,NaN,5987
155278,user_2163,prob_2495,1,30,23,0,13,422.878,422.878,intermediate,2529,D,NaN,*special,1185
155279,user_2163,prob_1822,1,30,23,0,13,422.878,422.878,intermediate,2529,C,NaN,*special,2013
155280,user_2163,prob_934,1,30,23,0,13,422.878,422.878,intermediate,2529,F,NaN,*special,3590
155281,user_2629,prob_4822,2,108,80,0,1,338.303,305.046,beginner,2089,B,NaN,NaN,2089
155282,user_1916,prob_3841,3,429,333,-3,37,433.773,433.773,intermediate,2429,C,NaN,NaN,3539
155283,user_2054,prob_3207,5,341,310,0,27,567.374,549.025,advanced,2398,H,NaN,NaN,1596
155284,user_2054,prob_2875,1,341,310,0,27,567.374,549.025,advanced,2398,J,NaN,NaN,2868
155285,user_2054,prob_470,2,341,310,0,27,567.374,549.025,advanced,2398,E,NaN,NaN,3167
155286,user_2738,prob_1131,3,44,38,0,2,457.856,399.083,intermediate,2439,E,3000.0,NaN,6277
155287,user_1731,prob_347,1,47,31,0,0,325.975,306.766,beginner,3499,A,NaN,NaN,928
155288,user_2777,prob_1903,1,331,288,18,151,650.516,617.833,expert,2372,G,NaN,NaN,371
155289,user_728,prob_1454,5,121,115,0,22,349.197,325.975,intermediate,1876,B,NaN,NaN,2441
155290,user_728,prob_571,2,121,115,0,22,349.197,325.975,intermediate,1876,K,NaN,NaN,3617
155291,user_728,prob_1125,2,121,115,0,22,349.197,325.975,intermediate,1876,F,NaN,NaN,103
155292,user_728,prob_4963,2,121,115,0,22,349.197,325.975,intermediate,1876,A,NaN,NaN,5256
155293,user_2273,prob_2720,3,398,334,0,27,492.546,441.227,intermediate,2316,G,NaN,NaN,5786
155294,user_518,prob_2233,1,27,18,0,2,317.374,299.599,beginner,289,F,3000.0,"dp,games,greedy,trees",2939

> Ótimo ! Todas os labels se referem a usuários+problemas existentes

In [9]:
train_aggregate, test_validation_aggregate = train_test_split(aggregate, test_size=0.3, shuffle=True)
test_aggregate, validation_aggregate = train_test_split(test_validation_aggregate, test_size=0.5, shuffle=True)
len(train_aggregate), len(test_aggregate), len(validation_aggregate)

(108706, 23294, 23295)

In [25]:
max_attempts_range = 6
min_attempts_range = 1
user_embedding_dimensionality = 50
problem_embedding_dimensionality = 50
dropout_embedding_rate = 0.5
hidden_dimensionality = 10
dropout_hidden_rate = 0.5

user_input = keras.layers.Input(shape=(1, ), dtype='int32')
problem_input = keras.layers.Input(shape=(1, ), dtype='int32')

user_embedding = keras.layers.Embedding(len(users), user_embedding_dimensionality) # input length ?
problem_embedding = keras.layers.Embedding(len(problems), problem_embedding_dimensionality) # input length ?

concat = keras.layers.Concatenate()
reshape = keras.layers.Reshape((user_embedding_dimensionality + problem_embedding_dimensionality, ))

dropout_embedding = keras.layers.Dropout(dropout_embedding_rate)

hidden_dense = keras.layers.Dense(hidden_dimensionality, activation='relu', use_bias=True)

dropout_hidden = keras.layers.Dropout(dropout_hidden_rate)

sigmoid = keras.layers.Dense(1, activation='sigmoid', use_bias=True)
softmax = keras.layers.Softmax()
chooseone = keras.layers.Maximum()

output = keras.layers.Lambda(lambda x: x * (max_attempts_range - min_attempts_range) + min_attempts_range)

network = output(
     sigmoid(
         dropout_hidden(
            hidden_dense(
                dropout_embedding(
                    reshape(
                        concat([user_embedding(user_input), problem_embedding(problem_input)])
                    )
                )
            )
        )
    )
)

#network = softmax(
#    dropout_hidden(
#        hidden_dense(
#            dropout_embedding(
#                reshape(
#                    concat([user_embedding(user_input), problem_embedding(problem_input)])
#                )
#            )
#        )
#    )
#)

model = keras.models.Model(inputs=[user_input, problem_input], outputs=network)
model.compile('rmsprop', loss='mse', metrics=['mse'])
# model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [26]:
logdir="logs/fit/" + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = keras.callbacks.TensorBoard(log_dir=logdir)

model.fit(
    [
        numpy.ndarray.flatten(train_aggregate[['user_id_num']].values), 
        numpy.ndarray.flatten(train_aggregate[['problem_id_num']].values)
    ], 
    numpy.ndarray.flatten(train_aggregate[['attempts_range']].values) - 1, 
    validation_data=(
        (
            numpy.ndarray.flatten(test_aggregate[['user_id_num']].values),
            numpy.ndarray.flatten(test_aggregate[['problem_id_num']].values)
        ),
        numpy.ndarray.flatten(test_aggregate[['attempts_range']].values) - 1
    ),
    epochs=100, 
    batch_size=32,
    callbacks=[
        # keras.callbacks.EarlyStopping(monitor='val_loss', patience=4),
        tensorboard_callback
    ]
)

Train on 108706 samples, validate on 23294 samples
Epoch 1/100
108706/108706 [==============================] - 10s 87us/sample - loss: 1.5200 - mse: 1.5200 - val_loss: 1.1843 - val_mse: 1.1843
Epoch 2/100
108706/108706 [==============================] - 8s 78us/sample - loss: 1.1876 - mse: 1.1876 - val_loss: 1.1538 - val_mse: 1.1538
Epoch 3/100
108706/108706 [==============================] - 9s 79us/sample - loss: 1.1668 - mse: 1.1668 - val_loss: 1.1474 - val_mse: 1.1474
Epoch 4/100
108706/108706 [==============================] - 8s 75us/sample - loss: 1.1559 - mse: 1.1559 - val_loss: 1.1507 - val_mse: 1.1507
Epoch 5/100
108706/108706 [==============================] - 8s 72us/sample - loss: 1.1510 - mse: 1.1510 - val_loss: 1.1519 - val_mse: 1.1519
Epoch 6/100
108706/108706 [==============================] - 9s 80us/sample - loss: 1.1479 - mse: 1.1479 - val_loss: 1.1524 - val_mse: 1.1524
Epoch 7/100
108706/108706 [==============================] - 9s 80us/sample - loss: 1.1459 - mse: 1.1459 - val_loss: 1.1539 - val_mse: 1.1539
Epoch 8/100
108706/108706 [==============================] - 8s 77us/sample - loss: 1.1449 - mse: 1.1449 - val_loss: 1.1553 - val_mse: 1.1553
Epoch 9/100
108706/108706 [==============================] - 9s 80us/sample - loss: 1.1444 - mse: 1.1444 - val_loss: 1.1543 - val_mse: 1.1543
Epoch 10/100
108706/108706 [==============================] - 9s 79us/sample - loss: 1.1438 - mse: 1.1438 - val_loss: 1.1547 - val_mse: 1.1547
Epoch 11/100
108706/108706 [==============================] - 9s 80us/sample - loss: 1.1405 - mse: 1.1405 - val_loss: 1.1552 - val_mse: 1.1552
Epoch 12/100
108706/108706 [==============================] - 10s 89us/sample - loss: 1.1410 - mse: 1.1410 - val_loss: 1.1560 - val_mse: 1.1560
Epoch 13/100
108706/108706 [==============================] - 10s 91us/sample - loss: 1.1429 - mse: 1.1429 - val_loss: 1.1558 - val_mse: 1.1558
Epoch 14/100
108706/108706 [==============================] - 9s 86us/sample - loss: 1.1420 - mse: 1.1420 - val_loss: 1.1548 - val_mse: 1.1548
Epoch 15/100
 42784/108706 [==========>...................] - ETA: 5s - loss: 1.1311 - mse: 1.1311

KeyboardInterrupt:

In [137]:
%tensorboard --logdir logs

In [115]:
validation_comparison = pandas.DataFrame([model.predict((
        numpy.ndarray.flatten(validation_aggregate[['user_id_num']].values), 
        numpy.ndarray.flatten(validation_aggregate[['problem_id_num']].values)
    )), numpy.ndarray.flatten(validation_aggregate[['attempts_range']].values)])
validation_comparison

                                                   0
0  [[1.6130446], [1.8696014], [2.4984562], [2.429...
1  [1, 1, 3, 1, 2, 1, 3, 1, 1, 2, 1, 1, 2, 3, 1, ...

In [111]:
validation_prediction = numpy.ndarray.round(
    model.predict((
        numpy.ndarray.flatten(validation_aggregate[['user_id_num']].values), 
        numpy.ndarray.flatten(validation_aggregate[['problem_id_num']].values)
    ))
)
validation_prediction

array([[2.],
       [2.],
       [2.],
       ...,
       [3.],
       [1.],
       [3.]], dtype=float32)

In [101]:
validation_truth = numpy.ndarray.flatten(validation_aggregate[['attempts_range']].values)

In [110]:
numpy.ndarray.flatten(numpy.array([x for x in map(lambda x: x[0] == x[1], zip(validation_prediction, validation_truth))]))

array([False, False, False, ..., False,  True, False])

In [105]:
model.evaluate(
    x=(
        numpy.ndarray.flatten(validation_aggregate[['user_id_num']].values), 
        numpy.ndarray.flatten(validation_aggregate[['problem_id_num']].values)
    ),
    y=numpy.ndarray.flatten(validation_aggregate[['attempts_range']].values)
)

23295/23295 [==============================] - 1s 29us/sample - loss: 0.9763 - mse: 0.9763

[0.9763076334788733, 0.9763081]

In [155]:
scipy.stats.mode(numpy.ndarray.flatten(train_aggregate[['attempts_range']].values)-1)

ModeResult(mode=array([0]), count=array([57773]))

In [158]:
len(numpy.ndarray.flatten(train_aggregate[['attempts_range']].values))

108706

In [159]:
57773/108706

0.5314610049123324